### ISSUE TITLE
Primary nav mask doesn't work in latest firefox.

### ISSUE THREAD

**Issue by jonathanbardo** [LiftUX/scribbles-theme#1]
![screen shot 2016-08-12 at 2 41 49 pm](https://cloud.githubusercontent.com/assets/1933681/17633365/ebcbce78-609a-11e6-982b-b017652ae9fe.png)

**Comment by frankiejarrett** [comment]
Possibly related to the SVG file itself: http://stackoverflow.com/a/15245847
