### ISSUE TITLE
Contact Me page not working

### ISSUE THREAD

**Issue by mrsbmw** [LiftUX/scribbles-theme#11]
I have created a wordpress site using the scribbles theme.    I added a Contact Me page, and it appears that when users create a contact entry, it is not arriving in my email.

Site is connectingquilters.net             email, hosted thru GoDaddy is  info@connectingquilters.net

Any insight you have would be helpful.    Thank you
(the less technical you answers are, the better!  Webpage creation is not my forte!)
Bonnie

**Comment by frankiejarrett** [comment]
Hi @mrsbmw, happy to help.

The first thing to do will be to ensure all of the plugins on your site are up-to-date, specifically the Ninja Forms plugin.

You can do this from the **Dashboard > Updates** screen in your WP Admin area.
